# Generated by Django 2.2 on 2021-06-12 03:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('mensaje', ckeditor.fields.RichTextField()),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
