# Generated by Django 2.2 on 2021-06-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_redessociales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redessociales',
            name='link',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
